export const dummyHospitals = [
  {
    id: 'hosp1',
    name: 'Pretoria General Hospital',
    location: { lat: -25.7479, lng: 28.2293 },
    totalUnits: 50,
    occupiedUnits: 35,
    address: '217 Bosman St, Pretoria',
    contactNumber: '+27 12 354 1000',
    type: 'public',
  },
  {
    id: 'hosp2',
    name: 'Life Groenkloof Hospital',
    location: { lat: -25.7863, lng: 28.2512 },
    totalUnits: 30,
    occupiedUnits: 28,
    address: 'George Storrar Dr, Groenkloof',
    contactNumber: '+27 12 354 3000',
    type: 'private',
  },
  {
    id: 'hosp3',
    name: 'Steve Biko Academic Hospital',
    location: { lat: -25.7344, lng: 28.2151 },
    totalUnits: 75,
    occupiedUnits: 45,
    address: 'Malherbe St, Pretoria',
    contactNumber: '+27 12 354 2000',
    type: 'public',
  },
];

export const dummyAmbulances = [
  {
    id: 'amb1',
    vehicleNumber: 'GP-AMB-001',
    driverId: 'driver1',
    driverName: 'John Smith',
    driverPhone: '+27 82 123 4567',
    provider: 'ER24',
    status: 'available',
    currentLocation: { lat: -25.7479, lng: 28.2293 },
    type: 'ALS', // Advanced Life Support
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'amb2',
    vehicleNumber: 'GP-AMB-002',
    driverId: 'driver2',
    driverName: 'Sarah Johnson',
    driverPhone: '+27 83 234 5678',
    provider: 'Netcare 911',
    status: 'dispatched',
    currentLocation: { lat: -25.7863, lng: 28.2512 },
    type: 'BLS', // Basic Life Support
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'amb3',
    vehicleNumber: 'GP-AMB-003',
    driverId: 'driver3',
    driverName: 'Michael Brown',
    driverPhone: '+27 84 345 6789',
    provider: 'ER24',
    status: 'available',
    currentLocation: { lat: -25.7344, lng: 28.2151 },
    type: 'ALS',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'amb4',
    vehicleNumber: 'GP-AMB-004',
    driverId: 'driver4',
    driverName: 'Emily Davis',
    driverPhone: '+27 85 456 7890',
    provider: 'Provincial EMS',
    status: 'busy',
    currentLocation: { lat: -25.7550, lng: 28.2400 },
    type: 'BLS',
    lastUpdated: new Date().toISOString(),
  },
];

export const dummyEmergencyCalls = [
  {
    id: 'call1',
    callerName: 'Anonymous',
    callerPhone: '+27 82 987 6543',
    location: { lat: -25.7479, lng: 28.2393 },
    address: '123 Main Street, Pretoria',
    description: 'Chest pain, difficulty breathing',
    priority: 'critical',
    status: 'dispatched',
    dispatchedAmbulance: 'amb2',
    timestamp: new Date(Date.now() - 300000).toISOString(),
    eta: '12 mins',
  },
  {
    id: 'call2',
    callerName: 'Anonymous',
    callerPhone: '+27 83 876 5432',
    location: { lat: -25.7550, lng: 28.2300 },
    address: '456 Oak Avenue, Pretoria',
    description: 'Vehicle accident, multiple injuries',
    priority: 'urgent',
    status: 'pending',
    timestamp: new Date(Date.now() - 60000).toISOString(),
  },
  {
    id: 'call3',
    callerName: 'Anonymous',
    callerPhone: '+27 84 765 4321',
    location: { lat: -25.7400, lng: 28.2200 },
    address: '789 Park Road, Pretoria',
    description: 'Elderly fall, possible fracture',
    priority: 'moderate',
    status: 'completed',
    dispatchedAmbulance: 'amb1',
    hospitalDestination: 'hosp1',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    completedAt: new Date(Date.now() - 1800000).toISOString(),
  },
];

export const dummyDrivers = [
  {
    id: 'driver1',
    name: 'John Smith',
    email: 'john.smith@er24.co.za',
    phone: '+27 82 123 4567',
    license: 'DL-12345',
    ambulanceId: 'amb1',
    status: 'active',
    dispatchCount: 45,
    avgResponseTime: '7 mins',
    forwardedCalls: 2,
  },
  {
    id: 'driver2',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@netcare.co.za',
    phone: '+27 83 234 5678',
    license: 'DL-23456',
    ambulanceId: 'amb2',
    status: 'active',
    dispatchCount: 38,
    avgResponseTime: '9 mins',
    forwardedCalls: 1,
  },
  {
    id: 'driver3',
    name: 'Michael Brown',
    email: 'michael.brown@er24.co.za',
    phone: '+27 84 345 6789',
    license: 'DL-34567',
    ambulanceId: 'amb3',
    status: 'active',
    dispatchCount: 52,
    avgResponseTime: '6 mins',
    forwardedCalls: 0,
  },
  {
    id: 'driver4',
    name: 'Emily Davis',
    email: 'emily.davis@ems.gov.za',
    phone: '+27 85 456 7890',
    license: 'DL-45678',
    ambulanceId: 'amb4',
    status: 'active',
    dispatchCount: 41,
    avgResponseTime: '8 mins',
    forwardedCalls: 3,
  },
];
